### ISSUE TITLE
Weekly Progress 3-5-2015

### ISSUE THREAD

**Issue by RachaelDinger** [CSUCyberSec/HPWebInterface#11]
We have just imaged a successful install of all components on the Raspberry Pi. Here is a breakdown of the major components that have been installed:
1) Snort
2) Barnyard2
3) PulledPork
4) MySQL
5) BASE (yes it's working correctly now, may replace this in the future)
6) Kippo
7) Kippo Graph
8) Apache2

Also -- we have successfully conducted Nmap scans of the Pi and we are recording to the database. Woohoo! That took forever, but its working now!

Next task it to clean up the tar balls and other set up garbage (that isn't needed) on the Pi, and re-image it. This image will be uploaded to the groups Google drive so that Chris can download and install when his PI arrives.

In the meantime:
1) Chris, have you checked out Snorby? They are a rubyonrails app that monitors networking. Pretty much what we want to do, it may be beneficial for you to check out their demo at : http://demo.snorby.org, user is demo@snorby.org, password is: snorby

Let us know what you think -- everyone else should check it out as well and see what features you think are good to implement in our app...

2) I'm taking the Pi home this weekend. I plan on sifting through all of the configuration and installation steps and compiling a list of what settings are needed to be set where. I want to eventually create a database table with these entries in them --> so we can write scripts that edit the config files and add these parameters based upon the values gathered by the set-up wizard from the user. Chris - this will also give you actual data fields to ask the user for and then have the wizard put in said database table. I think that the three of us here can handle creating the script generation of the stored values....

3) I think we should definitely have a group chat on Saturday evening if that works for everyone. Is 7:30 ok?

**Comment by RachaelDinger** [comment]
Also Chris - Can you please provide a summary of your weekly progress to this thread? Dr. Collins and Dr. Dubow are actively following our progress. Thanks!

**Comment by RachaelDinger** [comment]
while I still have all of this stuff fresh in my head, here are a couple of things I learned today:
- the Apache2 installation issue (seen as Apache2 defining localhost as 127.0.1.1) is caused by the variable ServerName not being defined in the Apache2 install. By adding a file called "servername.conf", and placing the line "ServerName localhost" inside -- you can fix this. I have more detailed directions I can provide if anyone wants them. 
-Snort does not have any capability to write to a database anymore. Therefore, in the snort config file you need to enable the output logging option as unified2 and then specify parameters. You must also set the output log path. <--- in the Barnyard2 conf file, you need to use this same log file path so Barnyard knows where to look. You must also enable "daemon" on Barnyard 2, as well as point to a valid .waldo path. -- Another thing to remember is that the eth0 should be enabled on both configs. 

-Sorry I posted so much. There was a lot done today!

**Comment by pyroesque** [comment]
I haven't made much progress on the interface yet. I started writing some of it the other day and came to the realization that I needed a more robust introduction to rails. I have spent a lot of time over the past week going through a better [Ruby on Rails Tutorial] (https://www.railstutorial.org/book) which I think will vastly help me out. I also found a wireframe/mockup program which I posted about in another issue. 

I don't think that Apache2 is necessary. Rails comes with it's own web server and I don't believe Apache would be able to host a rails application anyway. So you may not have to worry about that one. 

I did take a look at Snorby and I like what they have. I don't think we'll get anything quite as robust as that, but we can sure try.

**Comment by RachaelDinger** [comment]
MySQL and php are closely tied to apache2. Most front ends for the MySQL database require apache2 to work, I wouldn't advise uninstalling. I've spent over 30 hours of my time working with these components trying to get everything to work correctly together, so I'm only speaking from the standpoint of 'don't break the install'. I am still researching an alternate front end, as I would like to replace BASE. I am thinking about MySQL workbench, which will need apache2.

**Comment by RachaelDinger** [comment]
The web mock ups look really good. I should have a list of info to gather from the user for config settings shortly. Good job!
