### ISSUE TITLE
Want to add to FAQ? & Uploaded Help/FAQ and About html pages

### ISSUE THREAD

**Issue by miles00** [CSUCyberSec/HPWebInterface#16]
I uploaded very basic html Help/FAQ and About html pages (in the InterfacePages folder) that should be added to the interface (I was having trouble doing this myself). Open the html pages in a web browser to see what the content looks like. I invite anyone to add to the FAQ template (docx) if they feel like more information needs to be added. Let me know if you do this.
Thanks!

**Comment by pyroesque** [comment]
Thanks, I'll take a look and get them merged in.

**Comment by pyroesque** [comment]
I got these implemented into the code. They look pretty good, thanks for taking care of that.
