### ISSUE TITLE
Database Extension for Kippo 

### ISSUE THREAD

**Issue by RachaelDinger** [CSUCyberSec/HPWebInterface#2]
Hey guys - we still need to find a database extension for Kippo. Please put possible software/ideas on this thread rather than email.

**Comment by Jromo87** [comment]
I just found this tutorial on Logging Kippo events using MySQL DB it may be helpful
http://bruteforce.gr/logging-kippo-events-using-mysql-db.html

**Comment by Jromo87** [comment]
Also found this which discusses installing Kippo, Kippo Graph, and mysql on a kali-raspberrypi distro.

http://www.behindthefirewalls.com/2014/02/ssh-honeynet-kippo-kali-and-raspberry-pi.html
