### ISSUE TITLE
Updating rasbian image for the RPi2

### ISSUE THREAD

**Issue by Jromo87** [CSUCyberSec/HPWebInterface#4]
Hey guys I found this article on how to update the rasbian image to work with the raspberry pi.  It is hard to tell how well it works on a pre-made image but it is worth a try to hopefully save some time

http://thepihut.com/blogs/raspberry-pi-tutorials/16982376-updating-raspian-on-your-microsd-for-the-raspberry-pi-2

**Comment by RachaelDinger** [comment]
We can probably close this issue -- since we have just started from scratch.
