### ISSUE TITLE
Current Software Settings for Raspberry Pi Image

### ISSUE THREAD

**Issue by RachaelDinger** [CSUCyberSec/HPWebInterface#5]
For MySQL: 
login: root
password: honey

For Kippo's Database Table:
ip: localhost
database: kippo
user: kippo
password: Kippo-DB-pass

for the Kippo Honeypot:
login: <I need to double-check this -- could be "kippo">
password: honey

--settings for Kippo DB connection are found in /home/pi/kippo-read-only/data/userdb.txt
--settings for Kippo Honeypot found in /home/pi/kippo-read-only/kippo.cnfg
*we changed the default port for the Kippo Honeypot from 3306 to 2222 as instructed

*to access the Kippo graph html: 
http://<ip address of raspberry pi>/kippo-graph/kippo-graph.php

**Comment by Jromo87** [comment]
Supposedly people have been able to get mysql workbench is a good gui that works on rasbian
http://dev.mysql.com/downloads/workbench/

**Comment by Jromo87** [comment]
Authy Resources:
https://www.authy.com/help/getting-started
https://github.com/authy/rails-authy-get-started

**Comment by RachaelDinger** [comment]
ok thank you! We will install both tomorrow. Also -- we need to figure out the keyboard configuration and get that corrected.

**Comment by pyroesque** [comment]
sorry, but I'm going to veto authy. It's an API for two step authentication, like what you use for facebook, that requires using cell phone numbers and what not. It also looks like the user would need to have something installed on their computer as well. This is a little overkill for what we need and I'd rather not have to learn another API is possible. We can just stick with a simple username and password database for the time being, besides we'll have to know the username for the OS to manipulate settings.

**Comment by Jromo87** [comment]
I agree that having a stronger authentication process should not be first priority, but I feel this is not something that we should so quickly write off.  It is important that we show we are taking all the steps required to make our device as secure as possible.  If someone is able to hack our web interface and then have access to all of our config settings, then that would render our device useless.  

Authy is not really like facebook login.  The facebook login is basically just an easy way to log into accounts using only one login.  Authy, is a different form of authentication that adds an extra layer of security by generating random keys or 3d bar codes on your phone.  No additional software is necessary on a computer that you are using to access a webpage with authy authentication and the code to implement it didn't seem very technical. That is why I originally thought it would be something very useful and easy to implement.

Your comment has however,  encouraged me to revisit Authy implementation methods and unfortunately it looks like the company has been bought out by a company called Twilio over the last week and they now charge $0.05 per authentication.  Although this is not bank breaking, it is something we would need to maintain that we don't want to maintain.    Therefore it might be best to consider other options if there is time.  At very minimum, we should mention this as something to be considered for future revisions.

**Comment by miles00** [comment]
Perhaps we should keep this issue open then until it is resolved? Or at least remember to open it again later as it is probably necessary to have better security than a login and password. For now, we can develop using minimal security.

**Comment by pyroesque** [comment]
I think if the authentication of this like a normal computer or router. Both of those use a normal username and password scheme and are just fine. I agree we should make our device as secure as possible, but I believe that just means making sure our database is encrypted and username/passwords are encrypted during transmission. That should be all of the security necessary.

**Comment by RachaelDinger** [comment]
Chris -- we have postponed adding the source files for Authy for now. I do agree with both Miles and Jared that we should keep this issue open, however. Maybe there is another alternative out there for ensuring sufficient admin/system settings protections. During the installation process we created a password for the super user because we've had issues with permissions. When we are done installing we should revoke this permission however (or reset that user.. not sure how that works yet)

**Comment by pyroesque** [comment]
Welcome to Linux! It's all about the permissions in this world and it's going to be a bit of a headache. However, this is what will make our device more secure. Linux, by nature, is a fairly secure platform, that's why you don't hear a lot about Linux machines being hacked. I've been reading a bit on Rails and it seems we should be able to implement a sufficient username/password scheme that is secure just using what is already included in Rails, I'll hopefully have the proper knowledge to do this by the end of the week. Between that and Linux we should have a very secure little system. One thing to maybe think about is how would we go about testing and proving the security of our system?

**Comment by RachaelDinger** [comment]
We have the Cyber Security Desktop set up - and we also have the bootable Kali Linux distro. We can also boot Kali on that and run an nmap scan, or some other hacking attempt to test the Pi. However, we cannot do this on CSU's network. What we plan on doing (because this brings up another problem) is bringing in a router and setting up a separate private network behind it. This way the router can act as the gateway and we can have our Raspberry Pi connect to a static IP. The dynamic IP addressing that CSU's network uses is not great for the PI -- because each time we turn on the PI we are assigned a new IP -- this IP then has to be modified in different conf files. Right now, without automated scripts to handle this -- its becoming a major pain. 

One thing I think that we should do is check the ifconfig at boot for the current IP -- so that once launched, if the PI were to lose power on a dynamic IP it can either adjust (or at least reassign it's IP that the user wants it to use)

**Comment by miles00** [comment]
Hey guys,
I made a little progress on configuring the pi,
Check out the readme on the desktop of the pi and let me know if you have problems.

**Comment by pyroesque** [comment]
You can set a static IP on the Pi, look at [this tutorial](https://www.howtoforge.com/linux-basics-set-a-static-ip-on-ubuntu), I know it's on Ubuntu but it's the same concept. You have to modify the ifconfig to tell it to set a static IP. There are also many other ways of doing it, this was the easiest one I found, though it may take a little tinkering to get it working.

**Comment by RachaelDinger** [comment]
Thanks Chris, we will attempt that tomorrow. Miles, what items were you able to complete? Were you able to get Barnyard to talk to Snort yet?

**Comment by miles00** [comment]
Check out the readme I made on the desktop of the pi and let me know if u have questions.
