### ISSUE TITLE
Image Requests

### ISSUE THREAD

**Issue by RachaelDinger** [CSUCyberSec/HPWebInterface#9]
Chris -- as you work on the web interface please put requests for images/logos here. Please include a:

 1) general description (it can be vague) of what you need
 2) pixel size (w x d)
3) the output format --> I can give you a : .PNG-8bit File, PNG-24-bit File, a JPG File, or a GIF-8bit File (these are specifically formatted for webpages)

**Comment by pyroesque** [comment]
Great thanks! When I do have requests please put them into the [*apps/assets/images*](https://github.com/CSUCyberSec/HPWebInterface/tree/master/app/assets/images) folder

**Comment by RachaelDinger** [comment]
I will do that.
